<?php

namespace App\Providers;

use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\ServiceProvider;
use App\Models\Post;
use App\Models\Role;
use App\Models\User;
use App\Models\Permission;
use App\Observers\PostObserver;
use App\Observers\UserObserver;
use App\Observers\RolerObserver;
use App\Observers\PermissionObserver;
use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Support\Facades\URL;
use Laravel\Fortify\Fortify;

class AppServiceProvider extends ServiceProvider
{
    /**
     * The path to the "home" route for your application.
     *
     * Typically, users are redirected here after authentication.
     *
     * @var string
     */
    public const HOME = '/home';

    /**
     * Register any application services.
     */
    public function register(): void
    {

    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Post::observe(PostObserver::class);
        User::observe(UserObserver::class);
        Role::observe(RolerObserver::class);
        Permission::observe(PermissionObserver::class);
        $this->bootAuth();
        $this->bootRoute();
        /***/
        VerifyEmail::toMailUsing(function ($notifiable, $url) {
        // Parse the default local backend URL generated by Laravel
        $parsedUrl = parse_url($url);

        // Extract out the path query containing ID, signature hash, and expiration
        $pathAndQuery = $parsedUrl['path'] . '?' . ($parsedUrl['query'] ?? '');

        // Prepend your custom frontend URL (e.g., Nuxt, Next.js, Vue, or React app)
        $frontendUrl = env('FRONTEND_URL', 'http://localhost:3000') . $pathAndQuery;

        return (new MailMessage)
            ->subject('Verify Email Address')
            ->line('Please click the button below to verify your email address.')
            ->action('Verify Email Address', $frontendUrl)
            ->line('If you did not create an account, no further action is required.');
    });
    /*VerifyEmail::createUrlUsing(function ($notifiable) {
        // Points directly to your Vue frontend view router
        return redirect(env('FRONTEND_URL', 'http://localhost:3000')) . $notifiable->getKey() . '/' . sha1($notifiable->getEmailForVerification());
    });*/
            //Redirect or respond for the "Verify Email" notice screen
      Fortify::verifyEmailView(function () {
          return redirect(env('FRONTEND_URL','http://localhost:3000') . '/verify-email?status=' . session('status'));
});
        // verify email notification customization
        /*VerifyEmail::createUrlUsing(function ($notifiable) {
			$frontendUrl = env('FRONTEND_URL', 'http://localhost:3000');
			$verificationUrl = URL::temporarySignedRoute(
				'verification.verify',
				now()->addMinutes(config('auth.verification.expire', 60)),
				[
				    'id' => $notifiable->getKey(),
				    'hash' => sha1($notifiable->getEmailForVerification()),
				]
			);

			$queryString = parse_url($verificationUrl, PHP_URL_QUERY);

			// Replace the backend URL with the frontend URL
			return $frontendUrl . '/email/verify?' . $queryString;
			//return str_replace(config('app.url'), $frontendUrl, $verificationUrl);
		});*/

    //
    // For Vue SPA via Axios (redirect to frontend route)
   // Fortify::verifyEmailView(function () {
   //     return redirect(env('FRONTEND_URL') . '/email/verify');
   // });

    }// end of boot

    public function bootAuth()
    {
        // ResetPassword::createUrlUsing(function ($user, string $token) {
        //     return env('APP_URL').'/reset-password?token='.$token;
        // });
            ResetPassword::createUrlUsing(function (object $notifiable, string $token) {
                return env('FRONTEND_URL') . '/reset-password?token=' . $token . '&email=' . urlencode($notifiable->getEmailForPasswordReset());
            });
    }

    public function bootRoute()
    {
        RateLimiter::for('login', function (Request $request) {
            return Limit::perMinute(10);
        });
            RateLimiter::for('api', function (Request $request) {
                return Limit::perMinute(30);
            });
    }
}
